defaults:
  - exp_dec11
  - _self_
  
name: unet_ddim_ztsnr_lowdim

policy:
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddim.DDIMScheduler
    num_train_timesteps: 1024
    beta_start: 0.0001
    beta_end: 0.02
    # beta_schedule is important
    # this is the best we found
    beta_schedule: squaredcos_cap_v2
    clip_sample: True
    set_alpha_to_one: True
    steps_offset: 0
    prediction_type: v_prediction # or sample
    rescale_betas_zero_snr: True
